# Generated by Django 4.2 on 2024-10-04 10:45

import Categorie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, validators=[Categorie.models.validate_letters_only]),
        ),
    ]
