# Generated by Django 4.2 on 2024-10-04 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='capacity',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=900, message='capacity must be under 900')]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='program',
            field=models.FileField(error_messages='should contain certaintypes', upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])]),
        ),
    ]
