# Generated by Django 4.2 on 2024-10-11 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0002_alter_conference_capacity_alter_conference_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 11, 10, 25, 44, 434349, tzinfo=datetime.timezone.utc)),
        ),
    ]
