# Generated by Django 4.2 on 2024-10-15 16:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0007_alter_conference_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='program',
            field=models.FileField(error_messages='should contain certain types', upload_to='files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'jpeg', 'jpg'])]),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 15, 16, 50, 1, 109274, tzinfo=datetime.timezone.utc)),
        ),
    ]
