# Generated by Django 5.1.1 on 2024-10-22 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0017_alter_conference_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 22, 8, 37, 59, 746118, tzinfo=datetime.timezone.utc)),
        ),
    ]
