# Generated by Django 5.1.1 on 2024-10-22 09:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0018_alter_conference_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
