# Generated by Django 5.1.3 on 2024-12-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionOffres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offre',
            name='category',
            field=models.CharField(choices=[('kids', 'Kids'), ('teens', 'Teens'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
