# Generated by Django 5.1.3 on 2024-11-25 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Abonnements', '0001_initial'),
        ('gestionOffres', '0001_initial'),
        ('users', '0005_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonnements',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionOffres.offre'),
        ),
        migrations.AddField(
            model_name='abonnements',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client'),
        ),
        migrations.AlterUniqueTogether(
            name='abonnements',
            unique_together={('offre', 'participant')},
        ),
    ]
