# Generated by Django 5.1.3 on 2024-11-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_alter_comment_body'),
        ('theblog', '0012_post_created'),
    ]

    operations = [
    ]
