# Generated by Django 4.2 on 2024-10-04 10:45

import Participant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Resevations'},
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[Participant.models.Participant.email_validator]),
        ),
    ]
