# Generated by Django 4.2 on 2024-10-21 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Conference', '0015_alter_conference_start_date'),
        ('Participant', '0003_alter_reservation_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='conference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Conference.conference'),
        ),
    ]
