# Generated by Django 5.1.3 on 2024-11-25 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('abonnement_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'abonnements',
            },
        ),
    ]
